version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  tests: true
  allow-parallel-runners: true
  allow-serial-runners: true
  concurrency: 4

linters:
  default: standard
  enable:
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 10
